### ISSUE TITLE
kimai2 - plugin support planned?

### ISSUE THREAD

**Issue by clyso-dr** [robjuz/helm-charts#13]
Is there also a plugin support planned?
Plugins install: https://www.kimai.org/documentation/plugins.html

**Comment by robjuz** [comment]
This should be easy. Let me work on this on weekend.

**Comment by robjuz** [comment]
@clyso-dr 
There is a volume mounted under `/opt/kimai/var`
Persistence in also enabled per default, so a PVC and a PV should be created. You should be able to install plugins.

**Comment by clyso-dr** [comment]
I created the folder plugins and uploaded two plugins, there will be noticed but its not shown in the gui or are working:

```
$ pwd
/opt/kimai/var/plugins
$ ls -la
total 16
drwxrwsr-x  4 www-data www-data 4096 Jan 17 09:46 .
drwxrwsrwx  7 root     www-data 4096 Jan 17 07:49 ..
drwxrwsr-x  8 www-data www-data 4096 Jan 17 09:37 EasyBackupBundle
drwxrwsr-x 11 www-data www-data 4096 Jan 17 09:46 EmptyDescriptionCheckerBundle
```

"easy_backup", "empty_description_checker" are there after Kimai:reload:

```
  There is no extension able to load the configuration for "ldap" (in "/opt/kimai/config/packages/local.yaml"). Looked for namespace "ldap", found ""framework", "doctrine", "d
  octrine_migrations", "sensio_framework_extra", "monolog", "twig", "security", "admin_lte", "jms_serializer", "fos_rest", "nelmio_api_doc", "nelmio_cors", "webpack_encore", "
  twig_extra", "handcraftedinthealps_rest_routing", "easy_backup", "empty_description_checker", "kimai"".
```

**Comment by clyso-dr** [comment]
@robjuz is there an update here?

**Comment by robjuz** [comment]
I had no time to look on this. I will try this week.

**Comment by clyso-dr** [comment]
> I had no time to look on this. I will try this week.

thank you !

**Comment by clyso-dr** [comment]
works after fixing the ldap problem
