### ISSUE TITLE
Problem with deploy on Rancher with external DB

### ISSUE THREAD

**Issue by AndreaNocciolini** [robjuz/helm-charts#19]
Hello!
I'm opening this issue because I'm having serious problems deploying nominatim on Rancher using an external database. I've change the yaml file following the instructions on the readme file ([](https://github.com/robjuz/helm-charts/tree/master/charts/nominatim#readme)), but that doesn't work. **After a while the installation started, it tries to drop the database just created and it goes in error. If i delete the database while is restarting, it seems to overcome this step, but then another error appear, saying that it miss a www-data user**. </br>I'm trying since a while now, and i don't really know how to solve those problems, can i have any help? I am attaching a facsimile of the yaml with which I overwrite the data during initialization
<img width="543" alt="Schermata 2022-07-21 alle 11 04 41" src="https://user-images.githubusercontent.com/80393968/180175353-6c1100fc-5b96-4481-931e-eeebd60c4e7a.png">
.

**Comment by robjuz** [comment]
I will take a look

W dniu czw., 21.07.2022 o 11:05 AndreaNocciolini ***@***.***>
napisał(a):

**Comment by AndreaNocciolini** [comment]
Thank you very much!

**Comment by robjuz** [comment]
Hallo @AndreaNocciolini 

First of all thanks for interests in using this chart. 

I was able to perform a standard installation, so the install process is working 😄

Looking into the code I found, that the database name is hardcoded. I will fix it today. 

Im the meantime could you provide me some additional informations about your database instance? How you installed it? Does it have the necessary nominatim extension?

**Comment by AndreaNocciolini** [comment]
Hi @robjuz,
I'm glad that you're helping me!
About my database instance, unfortunately I can't provide much information because it was prepared for me by one of my colleagues. He installed the database on one of the amazon services (EC2) and he give me the data to connect to it. Once you've fix the problem I'll try again the installation, can you please tell me which extension are needed for Nominatim?

**Comment by robjuz** [comment]
https://nominatim.org/release-docs/latest/admin/Advanced-Installations/#using-an-external-postgresql-database

**Comment by robjuz** [comment]
@AndreaNocciolini
I releases a update. Please try now.

Some important things:
* The database is always nominatim. This comes from nominatim itself.
* The database user need superuser privilages to be able to create the postgis and hstore extension

**Comment by robjuz** [comment]
@AndreaNocciolini Any progress?

**Comment by AndreaNocciolini** [comment]
Hi @robjuz ! 
Sorry for the late reply, but I couldn't try as geofabrik blocked my IP :(. I'm trying to get in touch with them to get unblocked, once solved I'll let you know right away!

**Comment by robjuz** [comment]
@AndreaNocciolini Have you successes with the installation?

**Comment by AndreaNocciolini** [comment]
hello @robjuz , yes, we finish yestarday! The installation has been completed by my CTO, he was able to make it work (I messed up a bit with postgres DBs because of my inexperience :P)!
