### ISSUE TITLE
allow providing the database DSN via extraEnv

### ISSUE THREAD

**Issue by frank-bee** [robjuz/helm-charts#29]
Allow providing the database DSN via extraEnv.
Like this it could be provided as a k8s secret.
I will provide a PR for that

**Comment by robjuz** [comment]
Why would you set the database DSN manually, external database is already supported.

If security of the database password is your consent, I can improve the external database values to accept a secret with credentials.

**Comment by frank-bee** [comment]
> If security of the database password is your consent, I can improve the external database values to accept a secret with credentials.

Exactly, I  wanted to add the whole datacase DSN via reference to a secret. 
More as a simple workaround

**Comment by frank-bee** [comment]
But if you plan to refactor this anyway: 
Ideally the password for the external DB could be reference from a secret (optionally).
the is also another problem with the password: if it contains e.g. special characters, that leads to problems in the URL. I had to use only numbers as a workaround

**Comment by robjuz** [comment]
closing because of #48
