### ISSUE TITLE
[kimai2] helm update error

### ISSUE THREAD

**Issue by clyso-dr** [robjuz/helm-charts#31]
After an upgrade from helm chart version 1.4.6. to 1.4.7, kimai pod will not start due to an untrusted host error from the probes.

`ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\BadRequestHttpException: "Untrusted Host`

**Comment by robjuz** [comment]
Thanks for reporting

fixed in 1.4.8
