### ISSUE TITLE
kimai2: add option to override php.ini 

### ISSUE THREAD

**Issue by macmoritz** [robjuz/helm-charts#32]
PHPs default session timeout is set to 1440s/24m. To change this we need to override the php.ini file located in /usr/local/etc/php/php.ini in the kimai2 pod.

Implement an option in values.yaml to provide the php.ini config.

I will provide an pull request.

**Comment by robjuz** [comment]
Hallo @macmoritz 

Is this equivalent to setting the remember_me lifetime ?

```

configuration: -|
  security:
    firewalls:
        secured_area:
            remember_me:
                lifetime: 7776000

**Comment by macmoritz** [comment]
Hi @robjuz 
I dont find any docs to this. 
The kimai option (following) to set the session timeout does not take effect in your chart. (https://www.kimai.org/documentation/local-yaml.html#session-lifetime)
```
framework:
    session:
        gc_maxlifetime: 3600
        cookie_lifetime: 3600
```

**Comment by robjuz** [comment]
https://symfony.com/doc/current/security/remember_me.html

**Comment by macmoritz** [comment]
Hi there.
Thanks for your response. 
I dont see where the security part of your example (first comment in here) is loaded. 
Further, there is still the default session timeout of 24m.
Would be great if you can add additional informations.
