### ISSUE TITLE
[kimai] appVersion in Chart.yml does not correspond with image.tag in values.yml

### ISSUE THREAD

**Issue by f3k-tech** [robjuz/helm-charts#66]
Chart versions: 3.1.0, 3.1.1 & 3.1.2

I assume that the value of ```image.tag``` in **values.yml** should be updated to:  **apache-2.0.26-prod**

If you like I can add a new chart version, test and create a pull request (or change the existing ones in retrospect).

**Comment by robjuz** [comment]
fixed. thanks
