### ISSUE TITLE
Not able to Login

### ISSUE THREAD

**Issue by mayankkhullar** [robjuz/helm-charts#75]
Hello ,

I have tried installing kimai multiple times with below command 
helm upgrade --install   --set kimaiAdminEmail=admin --set kimaiPassword=password kimai robjuz/kimai2

**But I am not able to login with username and password and i am getting "invalid credentails" **

Helm output  getting like this 

** Please be patient while the chart is being deployed **

Your Kimai instance can be accessed through the following DNS name from within your cluster:

    kimai-kimai2.newrelic.svc.cluster.local (port 80)

To access your Kimai instance from outside the cluster follow the steps below:

1. Get the Kimai URL by running these commands:

  NOTE: It may take a few minutes for the LoadBalancer IP to be available.
        Watch the status with: 'kubectl get svc --namespace newrelic -w kimai-kimai2'

   export SERVICE_IP=$(kubectl get svc --namespace newrelic kimai-kimai2 --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
   echo "Kimai URL: http://$SERVICE_IP/"

2. Open a browser and access Kimai using the obtained URL.

3. Login with the following credentials below to see your blog:

  echo Username: admin
  echo Password: $(kubectl get secret --namespace newrelic kimai-kimai2 -o jsonpath="{.data.admin-password}" | base64 -d)

**Comment by robjuz** [comment]
Have you tried setting an email? Like ’admin@example.com’

**Comment by robjuz** [comment]
A.. I see it. I need to update the readme --set kimaiAdminPassword not kimaiPassword

**Comment by mayankkhullar** [comment]
Still same 
![image](https://github.com/robjuz/helm-charts/assets/5285057/c96d2dc9-9d86-4f6e-be65-70656363ad7c)

**Comment by mayankkhullar** [comment]
Issue resolved 

Thanks @robjuz
