### ISSUE TITLE
Can't able to integrate Azure AD | Helm Chart

### ISSUE THREAD

**Issue by mayankkhullar** [robjuz/helm-charts#78]
I was following doucmentation to integrate AZURE AD to kimai and i got to know there is a local.yaml file to be created with saml configurations as [er below docs

https://www.kimai.org/documentation/local-yaml.html
https://www.kimai.org/documentation/saml-azure.html

In the document its mentioned to copy and paste the file and does not contain how to pass this configuration as env variable of file mount to container.

<img width="900" alt="image" src="https://github.com/robjuz/helm-charts/assets/5285057/5e8efbdb-4981-431c-a4d9-66b0090f5cb6">

Could you please provide me the info

**Comment by robjuz** [comment]
You could try this. 
```
configurationFromSecret:
  ## @param configurationFromSecret.enabled Enables Kimai configuration retrieval from secret
  ## When the value is set to 'true', the secret name must match the common.names.fullname template and include a 'local.yaml' key.
  enabled: false
```

**Comment by robjuz** [comment]
Here is a MR that enabled it

https://github.com/robjuz/helm-charts/pull/60

**Comment by robjuz** [comment]
You can also use this one directly:

```
configuration: |-
  monolog:
      handlers:
          main:
              path: php://stderr
```

And add your saml config here.

**Comment by mayankkhullar** [comment]
Thanks @robjuz  but the configuration will be under main section or how ?? Can i have sample section or example ??

**Comment by robjuz** [comment]
You just put your `local.yaml` content under the `configuration` section in the `values.yaml` file. There are already the monolog settings. Just add your saml config. See the MR linked
