### ISSUE TITLE
Add plugin in Kimai via Helm

### ISSUE THREAD

**Issue by mayankkhullar** [robjuz/helm-charts#79]
Need to add the plugin in helm installation on k8s 
https://www.kimai.org/store/katjaglass-approval-bundle.html

i have created directory and /var/plugins and ran git clone in that directory and running the same image on k8s , its giving 

  **
  exec /usr/local/bin/docker-php-entrypoint: exec format error**

How can we simplify plugins installations on k8s installations made via helm ?

**Comment by robjuz** [comment]
I'm facing the same problem. For now a have persistence enabled and copy the plugin manually using kubectl.

I will adjust it to enable Plugins bundled directly in docker container.

**Comment by mayankkhullar** [comment]
after kubectl cp i have to restart the server and the issue is all the plugins will be deleted after that

**Comment by mayankkhullar** [comment]
yes pv is already there

**Comment by mayankkhullar** [comment]
oh i was doing in /var/plugins

**Comment by mayankkhullar** [comment]
so do i have to restart the pod after placing ? or it will pick automatically. ?

**Comment by robjuz** [comment]
You need to clear the cache. Either by restarting the pod or running the proper console command

**Comment by robjuz** [comment]
This is a strange error.

Can you give me more details? What is your `values.yaml`? Where are
deploying to?

**Comment by mayankkhullar** [comment]
It worked
