### ISSUE TITLE
Importing wikipedia importance data failing

### ISSUE THREAD

**Issue by david-mart** [robjuz/helm-charts#8]
This was an issue in Dockerfile 3.7, fixed in latest version. 

[Ref](https://github.com/mediagis/nominatim-docker/issues/271)

You should probably update the default image tag parameter.

UPD:
Tag 4.0 is still failing with the same issue

**Comment by david-mart** [comment]
After looking into this more, I figured out that the downloads of sql files are done by separate job steps. 
Created a pr #9 with the fix.

**Comment by robjuz** [comment]
Yes, I wrote dedicated kubernetes resources to handle the steps because of lack of flexibility in the base image.
