### ISSUE TITLE
[nominatim] allow to add annotations to PVCs

### ISSUE THREAD

**Issue by MatthiasLohr** [robjuz/helm-charts#83]
Hi @robjuz,

it would be great if it would be allowed to add annotations to the PVCs. This way, it is possible to set the `helm.sh/resource-policy: keep`, which keeps the annotated resource even with when running `helm uninstall`. Would you please consider adding that? Thanks!

Best regards
Matthias

**Comment by robjuz** [comment]
Hi @MatthiasLohr 
I started a big refactor on the `nominatim-refactor` branch. You can take a look on it.

**Comment by robjuz** [comment]
@MatthiasLohr Please take a look on the new release. There are may changes and new features. Unfortunatelly I don't have the possibility to test everything. Please let me know when something is wrong/not working.
