### ISSUE TITLE
[nominatim] Support sidecar containers

### ISSUE THREAD

**Issue by DevoFalcon** [robjuz/helm-charts#87]
It would be nice to have support for configuring a sidecar for Nominatim. A use-case would be using the GCP CloudSQL Auth Proxy (https://github.com/GoogleCloudPlatform/cloud-sql-proxy?tab=readme-ov-file#running-as-a-kubernetes-sidecar) to connect to a CloudSQL database for storage.

**Comment by robjuz** [comment]
@DevoFalcon Please take a look on the need release. There are may changes and new features. Unfortunatelly I don't have the possibility to test everything. Please let me know when something is wrong/not working.
